name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  CI:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      DENO_DIR: ~/.deno-cache
    steps:
      - uses: actions/checkout@v3
      - uses: bazelbuild/setup-bazelisk@v2
      - uses: denoland/setup-deno@v1
      - name: bazel cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/bazel
          key: bazel
      - name: deno cache
        uses: actions/cache@v3
        with:
          path: ${{ env.DENO_DIR }}
          key: ${{ hashFiles('deno.lock') }}
      - run: bazel build //wasm
      - run: ./copy-build.sh
      - run: deno test -A ts
      - run: deno run -A build.ts
        if: github.ref == 'refs/heads/main'
      - uses: dfm/force-push-branch-action@v1
        if: github.ref == 'refs/heads/main'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          target-branch: deno
          commit-message: Build
          path: |
            bin
            dist
            ts
      - name: Deno Deploy
        if: github.ref == 'refs/heads/main'
        uses: denoland/deployctl@v1
        with:
          project: protatoes
          entrypoint: ts/server.ts
